---

- name: Create AMQ Streams application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'amq-streams/amq-streams-application.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 60
  ignore_errors: true
  register: amq_streams_result
  until: amq_streams_result is not failed

- name: Print result from the previous task
  ansible.builtin.debug:
    var: amq_streams_result
