---

- name: Create Parasol AI application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'parasol-ai/parasol-ai-application.yml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: parasol_app_result
  until: parasol_app_result is not failed

- name: Print parasol_app_result from the previous task
  ansible.builtin.debug:
    var: parasol_app_result
