---

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Install AMQ Streams
  ansible.builtin.include_tasks: amq-streams.yml

- name: Install Parasol Application
  ansible.builtin.include_tasks: parasol.yml
